version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   # root 비밀번호
      MYSQL_DATABASE: mydb        # 기본 생성할 DB
      MYSQL_USER: hello           # 사용자 계정
      MYSQL_PASSWORD: world       # 사용자 비밀번호
      TZ: Asia/Seoul              # 컨테이너 OS 타임존
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-time-zone=+09:00   # MySQL 서버 타임존(KST)
    ports:
      - "3306:3306"   # 호스트:컨테이너 포트
    volumes:
      - db_data:/var/lib/mysql  # 데이터 영구 저장
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 초기화 스크립트(optional)
volumes:
  db_data:
